### ISSUE TITLE
Add to package set

### ISSUE THREAD

**Issue by ursi** [purescripters/purescript-template-strings#10]
Would you be interested in adding this to the package set? I just did it locally in a project and it worked fine out of the box.

```
{ template-strings =
  { dependencies = [ "functions", "tuples" ]
  , repo = "https://github.com/purescripters/purescript-template-strings.git"
  , version = "v5.1.0"
  }
}
```

I can add it myself if you tell me what group to put it in.

**Comment by Risto-Stevcev** [comment]
Sorry I'm not currently active with Purescript in general, someone else on this team might be able to help here. I sent you an invite.

**Comment by ursi** [comment]
No problem, I've since made my own package for this 👍
