### ISSUE TITLE
Cannot install because of a Bower conflict

### ISSUE THREAD

**Issue by stefanholzmueller** [purescripters/purescript-template-strings#4]
Hi, I cannot install this package because of a Bower conflict. Basically I tried:

    pulp init
    bower install purescript-template-strings

I am using pulp 10.0.1 and purescript 0.10.7. Any ideas? Maybe an upstream problem?

Full output:

> bower purescript-template-strings#*           cached https://github.com/purescripters/purescript-template-strings.git#2.0.0
bower purescript-template-strings#*         validate 2.0.0 against https://github.com/purescripters/purescript-template-strings.git#*
bower purescript-tuples#1.x                   cached https://github.com/purescript/purescript-tuples.git#1.0.0
bower purescript-tuples#1.x                 validate 1.0.0 against https://github.com/purescript/purescript-tuples.git#1.x
bower purescript-console#1.x                  cached https://github.com/purescript/purescript-console.git#1.0.0
bower purescript-console#1.x                validate 1.0.0 against https://github.com/purescript/purescript-console.git#1.x
bower purescript-functions#1.x                cached https://github.com/purescript/purescript-functions.git#1.0.0
bower purescript-functions#1.x              validate 1.0.0 against https://github.com/purescript/purescript-functions.git#1.x
bower purescript-foldable-traversable#^1.0.0  cached https://github.com/purescript/purescript-foldable-traversable.git#1.0.0
bower purescript-foldable-traversable#^1.0.0         validate 1.0.0 against https://github.com/purescript/purescript-foldable-traversable.git#^1.0.0
bower purescript-prelude#^1.0.0                        cached https://github.com/purescript/purescript-prelude.git#1.1.0
bower purescript-prelude#^1.0.0                      validate 1.1.0 against https://github.com/purescript/purescript-prelude.git#^1.0.0
bower purescript-eff#^1.0.0                            cached https://github.com/purescript/purescript-eff.git#1.0.0
bower purescript-eff#^1.0.0                          validate 1.0.0 against https://github.com/purescript/purescript-eff.git#^1.0.0
bower purescript-bifunctors#^1.0.0                     cached https://github.com/purescript-contrib/purescript-bifunctors.git#1.0.0
bower purescript-bifunctors#^1.0.0                   validate 1.0.0 against https://github.com/purescript-contrib/purescript-bifunctors.git#^1.0.0
bower purescript-maybe#^1.0.0                          cached https://github.com/purescript/purescript-maybe.git#1.0.0
bower purescript-maybe#^1.0.0                        validate 1.0.0 against https://github.com/purescript/purescript-maybe.git#^1.0.0
bower purescript-prelude#^2.4.0                        cached https://github.com/purescript/purescript-prelude.git#2.4.0
bower purescript-prelude#^2.4.0                      validate 2.4.0 against https://github.com/purescript/purescript-prelude.git#^2.4.0
bower purescript-monoid#^1.0.0                         cached https://github.com/purescript/purescript-monoid.git#1.0.0
bower purescript-monoid#^1.0.0                       validate 1.0.0 against https://github.com/purescript/purescript-monoid.git#^1.0.0
bower purescript-control#^1.0.0                        cached https://github.com/purescript/purescript-control.git#1.0.0
bower purescript-control#^1.0.0                      validate 1.0.0 against https://github.com/purescript/purescript-control.git#^1.0.0
bower purescript-invariant#^1.0.0                      cached https://github.com/purescript/purescript-invariant.git#1.0.0
bower purescript-invariant#^1.0.0                    validate 1.0.0 against https://github.com/purescript/purescript-invariant.git#^1.0.0
bower                                               ECONFLICT Unable to find suitable version for purescript-console

**Comment by Risto-Stevcev** [comment]
It needs to be updated to the latest compiler version, there was a breaking change. Thanks for filing a ticket, I'll update it

Just fyi if this happens for you with any other library, that's the cause. This issue is very similar to Haskell's cabal hell because the dependency tree is flat, and there's a curated package set like Hackage in the making for Purescript :slightly_smiling_face:

**Comment by stefanholzmueller** [comment]
Yeah, I've had similar problems with other packages... good to know :) Thanks!

**Comment by Risto-Stevcev** [comment]
I updated the dependencies so it should work now
